# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'PatientApp' do

#    pod 'AWSAutoScaling'
#    pod 'AWSCloudWatch'
#    pod 'AWSCognito'
#    pod 'AWSCognitoIdentityProvider'
#    pod 'AWSDynamoDB'
#    pod 'AWSEC2'
#    pod 'AWSElasticLoadBalancing'
#    pod 'AWSIoT'
#    pod 'AWSKinesis'
#    pod 'AWSLambda'
#    pod 'AWSMachineLearning'
#    pod 'AWSMobileAnalytics'
#    pod 'AWSS3'
#    pod 'AWSSES'
#    pod 'AWSSimpleDB'
#    pod 'AWSSNS'
#    pod 'AWSSQS'
    pod 'Datez'
    pod 'SVProgressHUD'
    pod 'DOAlertController'
end

target 'CaretakerApp' do
    pod 'Datez'
    pod 'ScrollableGraphView'
    pod 'ISTimeline', '~> 0.0.5'
    pod 'SVProgressHUD'
    pod 'DOAlertController'
end

